version: '3'

services:
  auth-service-db:
    container_name: auth-service-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: users_db
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  migrate:
    image: migrate/migrate
    depends_on:
      - auth-service-db
    volumes:
      - ./migrations:/migrations
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "mysql://root:root_password@tcp(auth-service-db:3306)/users_db"
      - "up"
